[package]
name = "city-game-core"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
geo-core.workspace = true
serde.workspace = true
serde-json.workspace = true
sha2.workspace = true
three-d-camera.workspace = true
three-d-core.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
geo-io-osm.workspace = true

[dev-dependencies]
osmpbfreader.workspace = true
protobuf.workspace = true

[[bench]]
name = "fixed_step"
harness = false

[[bench]]
name = "render_frame"
harness = false

[[bench]]
name = "save_render_roads"
harness = false
